### ISSUE TITLE
Unable to locate package uget-integrator

### ISSUE THREAD

**Issue by NatoBoram** [ugetdm/uget-integrator#55]
What I did : 

```bash
sudo add-apt-repository ppa:uget-team/ppa
sudo apt update
sudo apt install uget-integrator
```

What happened :

```bash
sudo apt install uget-integrator
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package uget-integrator
```

---

```yaml
OS: Ubuntu 18.10 x86_64 
Kernel: 4.18.0-12-generic 
Uptime: 10 hours, 48 mins 
Packages: 2214 (dpkg), 39 (snap) 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: GNOME 3.30.1 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3570K (4) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 3991MiB / 7921MiB 
```
